### ISSUE TITLE
[Feature Request] Biome whitelisting or blacklisting

### ISSUE THREAD

**Issue by Saereth** [JDKDigital/finitewater#1]
In some previous iterations of similar themed mods there was a config option to allow water to still be finite in certain biomes (e.g. River/Ocean biome) Would something like this be possible to get added to your version? Would be very useful. Thanks!

**Comment by JaisDK** [comment]
it's already supported, just add the biomes you want infinite water in to this tag.

https://github.com/JDKDigital/finitewater/tree/dev-1.20.1/src/main/resources/data/finitewater/tags/worldgen/biome
